export default {
  testimonials: [
    {
      name: 'John Doe',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      name: 'Jane Smith',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      name: 'Mike Johnson',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      name: 'John Doe',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      name: 'Jane Smith',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      name: 'Mike Johnson',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      name: 'Emily Davis',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      name: 'Sarah Brown',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      name: 'David Thompson',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      name: 'Jennifer Wilson',
      image: 'https://via.placeholder.com/150',
      content:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
  ],
  arts: [
    {
      id: 1,
      title: 'Serenity Landscape',
      description: 'An embodiment of calm and serenity.',
      image:  'https://source.unsplash.com/random/1000x1000?landscape',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 2,
      title: 'Urban Sunrise',
      description: 'City awakens with the first light.',
      image:  'https://source.unsplash.com/random/1000x1000?sunrise',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 3,
      title: "Ocean's Breath",
      description: 'The depth and mystery of the ocean.',
      image:  'https://source.unsplash.com/random/1000x1000?ocean',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 4,
      title: 'Starry Dreams',
      description: 'A night under the blanket of stars.',
      image:  'https://source.unsplash.com/random/1000x1000?stars',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 5,
      title: 'Whimsical Forest',
      description: 'The enchantment of untouched woods.',
      image:  'https://source.unsplash.com/random/1000x1000?forest',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 6,
      title: 'Desert Mirage',
      description: 'The beauty of barren expanses.',
      image:  'https://source.unsplash.com/random/1000x1000?desert',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 7,
      title: "Winter's Tale",
      description: 'The silent narrative of snow.',
      image:  'https://source.unsplash.com/random/1000x1000?winter',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 8,
      title: "Aurora's Dance",
      description: 'Lights that waltz across polar skies.',
      image:  'https://source.unsplash.com/random/1000x1000?aurora',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 9,
      title: "Mountain's Echo",
      description: 'The towering strength of nature.',
      image:  'https://source.unsplash.com/random/1000x1000?mountain',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 10,
      title: "Meadow's Song",
      description: 'The gentle hymn of the open fields.',
      image:  'https://source.unsplash.com/random/1000x1000?meadow',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 11,
      title: 'Golden Sunset',
      description: 'The warm embrace of a setting sun.',
      image:  'https://source.unsplash.com/random/1000x1000?sunset',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 12,
      title: 'Abstract Fusion',
      description: 'A blend of colors and shapes in harmony.',
      image:  'https://source.unsplash.com/random/1000x1000?abstract',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 13,
      title: 'Enchanted Waterfall',
      description: 'The cascading beauty of a hidden oasis.',
      image:  'https://source.unsplash.com/random/1000x1000?waterfall',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 14,
      title: 'Cherry Blossom Serenade',
      description: 'The delicate dance of blooming cherry blossoms.',
      image:  'https://source.unsplash.com/random/1000x1000?blossom',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 15,
      title: 'Fire and Ice',
      description: 'Contrasting elements in a captivating display.',
      image:  'https://source.unsplash.com/random/1000x1000?fire',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 16,
      title: 'Magical Moonlight',
      description: 'The mysterious allure of moonlit nights.',
      image:  'https://source.unsplash.com/random/1000x1000?moonlight',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 17,
      title: 'Vibrant Cityscape',
      description: 'The energy and vibrancy of a bustling city.',
      image:  'https://source.unsplash.com/random/1000x1000?city',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 18,
      title: 'Harmony in Chaos',
      description: 'Finding balance amidst a chaotic world.',
      image:  'https://source.unsplash.com/random/1000x1000?chaos',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 19,
      title: 'Majestic Waterfall',
      description: 'The awe-inspiring power of nature.',
      image:  'https://source.unsplash.com/random/1000x1000?waterfall',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
    {
      id: 20,
      title: 'Sunflower Symphony',
      description: 'A vibrant ode to the sunflower fields.',
      image:  'https://source.unsplash.com/random/1000x1000?sunflower',
      tags: ['Popular', 'New', 'Abstract', 'Nature', 'Parenting', 'For Kids', 'Culture', 'Puerto Rico'],
    },
  ],
  faq: [
    {
      question: 'What is the refund policy?',
      answer:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      question: 'Do you offer free shipping?',
      answer:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      question: 'What is the return policy?',
      answer:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
    {
      question: 'Do you offer gift cards?',
      answer:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu euismod sem.',
    },
  ],
  notifications: [
    {
      message: 'Your order #123456789 has been confirmed',
      type: 'order',
      created_at: '2023-11-10',
      is_read: false,
      user_id: 'alley',
    },
    {
      message: 'Your order #987654321 has been shipped',
      type: 'order',
      created_at: '2023-11-11',
      is_read: false,
      user_id: 'alley',
    },
    {
      message: 'Your wall art is due for return',
      type: 'reminder',
      created_at: '2023-11-13',
      is_read: false,
      user_id: 'alley',
    },
    {
      message: 'Shipping update for order #1122334455',
      type: 'order',
      created_at: '2023-11-12',
      is_read: false,
      user_id: 'alley',
    },
    {
      message: 'Monthly auto-pay reminder',
      type: 'reminder',
      created_at: '2023-11-14',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Your wall art is due for return',
      type: 'reminder',
      created_at: '2023-11-15',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Your order #3344556677 has been delivered',
      type: 'order',
      created_at: '2023-11-16',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Your subscription has been renewed',
      type: 'reminder',
      created_at: '2023-11-10',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Your order #1213141516 is on its way',
      type: 'order',
      created_at: '2023-11-17',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Return window for order #1213141516 closing soon',
      type: 'reminder',
      created_at: '2023-11-18',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Payment confirmation for order #1718192021',
      type: 'order',
      created_at: '2023-11-19',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Auto-pay reminder for your subscription',
      type: 'reminder',
      created_at: '2023-11-20',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Your order #2223242526 has been canceled',
      type: 'order',
      created_at: '2023-11-21',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Payment failed for order #2627282920',
      type: 'order',
      created_at: '2023-11-22',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Subscription expiration reminder',
      type: 'reminder',
      created_at: '2023-11-23',
      is_read: true,
      user_id: 'alley',
    },
    {
      message: 'Your order #3031323334 has been confirmed',
      type: 'order',
      created_at: '2023-11-24',
      is_read: true,
      user_id: 'alley',
    },
  ],
  cart: {
    arts: [
      {
        cart_id: '1234567890',
        art_id: 1,
        category: 'New',
        size: 'Small',
        quantity: 1,
        duration: 3,
        image: 'https://source.unsplash.com/random/51x50?landscape',
      },
      {
        cart_id: '1234567890',
        art_id: 1,
        category: 'New',
        size: 'Medium',
        quantity: 2,
        duration: 6,
        image: 'https://source.unsplash.com/random/50x51?landscape',
      },
      {
        cart_id: '1234567890',
        art_id: 1,
        category: 'New',
        size: 'Large',
        quantity: 1,
        duration: 3,
        image: 'https://source.unsplash.com/random/52x50?landscape',
      },
      {
        cart_id: '1234567890',
        art_id: 1,
        category: 'New',
        size: 'Small',
        quantity: 1,
        duration: 3,
        image: 'https://source.unsplash.com/random/50x52?landscape',
      },
      {
        cart_id: '1234567890',
        art_id: 1,
        category: 'New',
        size: 'Medium',
        quantity: 2,
        duration: 6,
        image: 'https://source.unsplash.com/random/53x50?landscape',
      },
      {
        cart_id: '1234567890',
        art_id: 1,
        category: 'New',
        size: 'Large',
        quantity: 1,
        duration: 3,
        image: 'https://source.unsplash.com/random/50x53?landscape',
      },
  ],
  },
  sidebar: {
    Popular: { icon: 'star', color: 'blue' },
    New: { icon: 'new_releases', color: 'green' },
    Abstract: { icon: 'palette', color: 'purple' },
    Nature: { icon: 'landscape', color: 'green' },
    Parenting: { icon: 'family_restroom', color: 'red' },
    Culture: { icon: 'public', color: 'blue' },
    'For Kids': { icon: 'child_care', color: 'pink' },
    'Puerto Rico': { icon: 'beach_access', color: 'yellow' },
  },
};
